# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bitly-api-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'BitlySDK'

  # Pods for bitly-api-app

  target 'bitly-api-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bitly-api-appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
